name: Run Tests
on:
  push:
    branches: [ main ]
    paths:
      - "build.gradle.kts"
      - "gradle.lockfile"
      - "settings.gradle.kts"
      - "src/**"
      - "gradle/**"
  pull_request:
    branches: [ main ]
    paths:
      - "build.gradle.kts"
      - "gradle.lockfile"
      - "settings.gradle.kts"
      - "src/**"
      - "gradle/**"
env:
  JAVA_VERSION: 16
  JAVA_PACKAGE: jdk
  JAVA_ARCH: x64
  JAVA_DISTRO: adopt
jobs:
  tests:
    name: ${{ matrix.os }} (${{ matrix.browser }}/${{ matrix.language }}/${{ matrix.device }})
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-latest, macos-latest ]
        browser: [ firefox, chrome ]
        device: [ mobile, tablet, desktop ]
        language: [ en, de, fr ]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v2.3.4
    - name: Set up Java
      uses: actions/setup-java@v2
      with:
        java-version: ${{ env.JAVA_VERSION }}
        java-package: ${{ env.JAVA_PACKAGE }}
        architecture: ${{ env.JAVA_ARCH }}
        distribution: ${{ env.JAVA_DISTRO }}
    - name: Cache Gradle packages
      uses: actions/cache@v2.1.5
      with:
        path: |
          ~/.gradle/caches
          ~/.gradle/wrapper
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
        restore-keys: |
          ${{ runner.os }}-gradle-
    - name: Build with Gradle
      run: ./gradlew test -Dbrowser=${{ matrix.browser }} -Dlang=${{ matrix.language }} -Ddevice=${{ matrix.device }}
    - name: Cleanup Gradle Cache
      # Remove some files from the Gradle cache, so they aren't cached by GitHub Actions.
      # Restoring these files from a GitHub Actions cache might cause problems for future builds.
      run: |
        rm -f ~/.gradle/caches/modules-2/modules-2.lock
        rm -f ~/.gradle/caches/modules-2/gc.properties
    - name: Upload Cucumber NDJSON
      uses: actions/upload-artifact@v2
      with:
        name: cucumber-ndjson-${{ matrix.browser }}-${{ matrix.language }}-${{ matrix.device }}
        path: ./build/reports/cucumber.ndjson
    - name: Upload Cucumber HTML
      uses: actions/upload-artifact@v2
      with:
        name: cucumber-html-${{ matrix.browser }}-${{ matrix.language }}-${{ matrix.device }}
        path: ./build/reports/cucumber.html
    - name: Upload Timeline Report
      uses: actions/upload-artifact@v2
      with:
        name: cucumber-timeline-${{ matrix.browser }}-${{ matrix.language }}-${{ matrix.device }}
        path: ./build/reports/timeline/*
    - name: Upload Gradle Test Report
      uses: actions/upload-artifact@v2
      with:
        name: gradle-test-report-${{ matrix.browser }}-${{ matrix.language }}-${{ matrix.device }}
        path: ./build/reports/tests/test/*
